spring.application.name=blackjack-simulation-project
spring.datasource.url=jdbc:postgresql://localhost:5432/blackjack_sim
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update