package com.amaris.blackjack_simulation_project.repository;


import java.util.ArrayList;
import java.util.List;
import java.util.Map;

//Class to convert data from "table" object into a format that can be stored in the database
//TODO add the annotations for JPA
public class GameSession {

    //Id for the game session can be autogenerated probably will be an integer
    private Long id;

    //Initial shoe order will be used to re-create rounds
    private String initialShoe;


    //Map of the rules used to convert them from an object into a jsonb for postgres
    private Map<String, Object> rules;

    // List of all the rounds that happened during a "session"
    private final List<RoundEntity> rounds = new ArrayList<>();


}
