package com.amaris.blackjack_simulation_project.repository;


import java.util.ArrayList;
import java.util.List;

// Class to represent each individual round of a shoe
public class RoundEntity {
    //ID for the round can probably be autogenerated as it will only ever be used internally in the program
    //possibly session ID + an additional two to three digits to indicate the round
    private long id;
    // Where the index of the shoe starts off used to jump to this round
    private int shoeIndexAtStart;
    // id of the game session this round belongs to
    private int SessionID;
    //Where each player currently is
    private List<SeatingEntity> seatingChart;
    //What the dealer ended up with in string form of final score then cards in hand  eg "17,seven, five"
    private String dealerFinalHand;
    //List of each player hand in the round
    private final List<PlayerHandEntity> playerHands = new ArrayList<>();

}
